global:
  image: "hashicorp/consul:1.14.0"
  peering:
    enabled: true
  tls:
    enabled: true

server:
  replicas: 1
  bootstrapExpect: 1
  extraConfig: |
    {
      "log_level": "TRACE"
    }

connectInject:
  enabled: true
  default: true

meshGateway:
  enabled: true
  replicas: 1

controller:
  enabled: true

ui:
  enabled: true
  service:
    enabled: true
    type: LoadBalancer